name: Goose Do It
# trigger when there is a labelled issue, or a comment 
on:
  issues:
    types:
      - labeled
  issue_comment:
    types:
      - created      
jobs:
  ask-goose:
    # this will run when an issue is labelled 'goose' or if a comment in a pull request asks for help from @goose-ai
    if: github.event.label.name == 'goose' || (github.event.issue.pull_request && contains(github.event.comment.body, '@goose-ai'))
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      ## Install Python if needed
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'  # Use Python 3.11 for better compatibility
      
      ## Install and configure pipx with goose-ai
      - name: Install goose-ai with pipx
        run: |
          # Ensure pipx is properly configured
          pipx ensurepath --force
          echo "$HOME/.local/bin" >> $GITHUB_PATH
          
          # Install goose-ai
          pipx install goose-ai
          
          # Inject the correct langfuse version to fix the compatibility issue
          pipx inject goose-ai langfuse==2.59.7
          
          # Verify installation
          which goose
          goose --version || true
        shell: bash
      
      ## Install whatever you need here as per your CI setup for your project
      
      
      - name: Run Goose Action
        uses: michaelneale/goose-fix-it-action@main
        with:
          task_request: |
            ${{ github.event.issue.title }}
            ${{ github.event.issue.body }}
            [Link to issue](${{ github.event.issue.html_url }})
          validation: "check the vite web app installs"          
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}  # or use ANTHROPIC_API_KEY
          GH_TOKEN: ${{ github.token }} # can change this to secrets.PAT if you want to trigger workflows
