name: Goose Do It

# trigger when there is a labelled issue, or a comment 
on:
  issues:
    types:
      - labeled
  issue_comment:
    types:
      - created      

jobs:
  ask-goose:
    # this will run when an issue is labelled 'goose' or if a comment in a pull request asks for help from @goose-ai
    if: github.event.label.name == 'goose' or ${{ github.event.issue.pull_request && contains(github.event.comment.body, '@goose-ai') }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      ## Install whatever you need here as per your CI setup for your project

      - name: Run Goose Action
        uses: michaelneale/goose-fix-it-action@main
        with:
          task_request: |
            ${{ github.event.issue.title }}
            ${{ github.event.issue.body }}
            [Link to issue](${{ github.event.issue.html_url }})
          validation: "check the vite web app installs"          
        env:
          OPENAI_API_KEY: ${{ secrets.REPLACE_WITH_PROVIDER_API_KEY }}
          GH_TOKEN: ${{ github.token }} # can change this to secrets.PAT if you want to trigger workflows
